mindmap
  root((Daily Routine))
    Morning
      Tasks
      Habits
      Activities
    Afternoon
      Tasks
      Habits
      Activities
    Evening
      Tasks
      Habits
      Activities
    Night
      Tasks
      Habits


